---
- name: Create Ubuntu Docker Containers
  hosts: nopasaran_nodes
  tasks:
    - name: Create Docker Containers
      docker_container:
        name: "nopasaran-{{ item }}"
        image: benilies/nopasaran
        state: started
        command: sleep infinity
        network_mode: host
      loop: "{{ range(1, 4) | list }}"
