name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image for benilies/nopasaran-node
        run: docker build . --file Dockerfile.node --tag benilies/nopasaran-node:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push benilies/nopasaran-node:latest

  build-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image for benilies/nopasaran-manager
        run: docker build . --file Dockerfile.pool-manager --tag benilies/nopasaran-manager:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push benilies/nopasaran-manager:latest
